version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: produtos
      MYSQL_USER: root
      MYSQL_PASSWORD: test
    ports:
      - 3306:3306
    volumes:
      -.docker/mysql:/var/lib/mysql